//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnS_Multitool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BnS_Multitool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _7za {
            get {
                object obj = ResourceManager.GetObject("7za", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BnS_Multi_Tool_Updater {
            get {
                object obj = ResourceManager.GetObject("BnS_Multi_Tool_Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] class_removes {
            get {
                object obj = ResourceManager.GetObject("class_removes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 901679848022474752.
        /// </summary>
        public static string discord_clientId {
            get {
                return ResourceManager.GetString("discord_clientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gq4mVqoDBrWN7oKV0jLzqtOMzsj65Bwk.
        /// </summary>
        public static string discord_secret {
            get {
                return ResourceManager.GetString("discord_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;config&gt;
        ///    &lt;options&gt;
        ///        &lt;!-- Reload Config Keybind [CTRL + ALT + 9]--&gt;
        ///        &lt;option name=&quot;reloadKey&quot; keyCode=&quot;39&quot; bCtrl=&quot;1&quot; bShift=&quot;0&quot; bAlt=&quot;1&quot; /&gt;
        ///        &lt;!-- Profile 1 Keybind [CTRL + ALT + 1]--&gt;
        ///        &lt;option name=&quot;profile_1&quot; keyCode=&quot;31&quot; bCtrl=&quot;1&quot; bShift=&quot;0&quot; bAlt=&quot;1&quot; /&gt;
        ///        &lt;!-- Profile 2 Keybind [CTRL + ALT + 2]--&gt;
        ///        &lt;option name=&quot;profile_2&quot; keyCode=&quot;32&quot; bCtrl=&quot;1&quot; bShift=&quot;0&quot; bAlt=&quot;1&quot; /&gt;
        ///        &lt;!-- Profile 3 Keybind [CTRL + ALT + 3] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string extended_options {
            get {
                return ResourceManager.GetString("extended_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://multitool.tonic.pw/.
        /// </summary>
        public static string MainServerAddr {
            get {
                return ResourceManager.GetString("MainServerAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;config&gt;
        ///    &lt;options&gt;
        ///        &lt;option name=&quot;useAutoBait&quot; enable=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;useItemCap&quot; enable=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;useMarketplace&quot; enable=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;AutoCombat&quot; enable=&quot;0&quot; useRange=&quot;0&quot; range=&quot;30&quot; TurnOffOnDeath=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;useNoCameraLock&quot; enable=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;useNoWallRunStamina&quot; enable=&quot;0&quot; /&gt;
        ///		&lt;option name=&quot;useWindowClipboard&quot; enable=&quot;0&quot; /&gt;
        ///        &lt;option name=&quot;useDebug&quot; enable=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string multitool_qol {
            get {
                return ResourceManager.GetString("multitool_qol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;?include .\patches\*.xml?&gt;
        ///&lt;patches&gt;
        ///  &lt;patch file=&quot;system.config2.xml&quot;&gt;
        ///    &lt;select-node query=&quot;/config&quot;&gt;
        ///      &lt;!-- don&apos;t show eula --&gt;
        ///      &lt;select-node query=&quot;./option[@name=&apos;show-clause&apos;]/@value&quot;&gt;
        ///        &lt;set-value value=&quot;false&quot; /&gt;
        ///      &lt;/select-node&gt;
        ///      &lt;!-- disable nagle algorithm in arena --&gt;
        ///      &lt;select-node query=&quot;./option[@name=&apos;use-nagle-arena&apos;]/@value&quot;&gt;
        ///        &lt;set-value value=&quot;false&quot; /&gt;
        ///      &lt;/select-node&gt;
        ///      &lt;!-- simple mode at [rest of string was truncated]&quot;;.
        /// </summary>
        public static string patches {
            get {
                return ResourceManager.GetString("patches", resourceCulture);
            }
        }
    }
}
